export * from "./home/home";
export * from "./about/about";
export * from "./about/card";
export * from "./about/dolly";
export * from "./management/categories";
export * from "./management/projects";
export * from "./global/navbar";
export * from "./global/footer";
export * from "./global/mailbox";
